To-Do/To-Do/Models/ToDoTask.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MySql.Data.Types;
using Pomelo.EntityFrameworkCore.MySql.Internal;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace To_Do.Models
{
    public class ToDoTask
    {
        public int Id { get; set; }
        public string OwnerID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool IsImportant { get; set; }
        public bool IsCompleted { get; set; }
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public DateTime LastEditedOn { get; set; } = DateTime.Now;
        public Folder Folder { get; set; }
        public int? FolderId { get; set; }

        public ToDoTask()
        {
        }

        public override bool Equals(object obj)
        {
            return obj is ToDoTask @do &&
                   Id == @do.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
        public override string ToString()
        {
            return Title;
        }
    }
}

To-Do/To-Do/Controllers/ToDoTaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.RenderTree;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using To_Do.Areas.Identity.Data;
using To_Do.Authorization;
using To_Do.Data;
using To_Do.Models;
using To_Do.ViewModels;

namespace To_Do.Controllers
{
    public class ToDoTaskController : Controller
    {
        private ApplicationRepository _repo;
        protected IAuthorizationService AuthorizationService { get; }
        protected UserManager<To_DoUser> UserManager { get; }
        public ToDoTaskController(ApplicationDbContext dbContext, IAuthorizationService authorizationService, UserManager<To_DoUser> userManager)
        {
            _repo = new ApplicationRepository(dbContext);
            AuthorizationService = authorizationService;
            UserManager = userManager;
        }

        //GET /<controller>/

        public async Task<IActionResult> Index(List<ToDoTask> searchSet = null)
        {
            ViewBag.title = "Tasks";
            IComparer<ToDoTask> comparer = new ToDoTaskComparer();
            //we can't set default value to _repo.Getodos, so if its null, we set the default value
            if(!searchSet.Any())
            {
                var currentUserId = UserManager.GetUserId(User);
                List<ToDoTask> todos = (List<ToDoTask>)await _repo.GetTodos(currentUserId);
                todos.Sort(comparer);
                ViewBag.title = "All tasks " + "(" + todos.Count() + ")";
                return View(todos);
            }
            else
            {
                ViewBag.userInput = "default";
                searchSet.Sort(comparer);
                return View(searchSet);
            }
        }
        //For 1/2/2023. When the search query does not return any tasks in "All tasks", everything is returned instead of showing "Nothing here yet!". Needs fix
        public async Task<IActionResult> SearchIndex(string serializedSearchSet)
        {
            List<ToDoTask> searchSet = JsonConvert.DeserializeObject<List<ToDoTask>>(serializedSearchSet);
            //ViewBag.title = "Tasks";
            IComparer<ToDoTask> comparer = new ToDoTaskComparer();
            //we can't set default value to _repo.Getodos, so if its null, we set the default value
            if (!searchSet.Any())
            {
                var currentUserId = UserManager.GetUserId(User);
                List<ToDoTask> todos = (List<ToDoTask>)await _repo.GetTodos(currentUserId);
                todos.Sort(comparer);
                ViewBag.title = "All tasks search results: (" + todos.Count() + ")";
                return View("Index",todos);
            }
            else
            {
                ViewBag.title = "All tasks search results: (" + searchSet.Count() + ")";
                ViewBag.userInput = "default";
                searchSet.Sort(comparer);
                return View("Index",searchSet);
            }
        }

        //GET /<controller>/Add
        public IActionResult Add(int? folderId = null)
        {
            ViewBag.folderId = folderId;
            List<Folder> folders = _repo.GetFoldersByUserId(UserManager.GetUserId(User)).ToList();
            return View(new AddToDoTaskViewModel(folders));
        }

        //POST /<controller>/Add
        [HttpPost]
        public async Task<IActionResult> Add(AddToDoTaskViewModel viewModel, int? folderId = null)
        {
            Folder folder;
            int? folderIdVal = null;
            if(folderId != null)
            {
                //User created task while in a folder, use that folder by default
                folder = _repo.GetFolderById(folderId);  
                folderIdVal = folder.Id;
            }

            if (ModelState.IsValid)
            {
                ToDoTask newTask = new ToDoTask
                {
                    Title = viewModel.Title,
                    Body = viewModel.Body,
                    IsImportant = viewModel.IsImportant,
                    FolderId= folderIdVal, 
                    OwnerID = UserManager.GetUserId(User)
                };
                
                var isAuthorized = await AuthorizationService.AuthorizeAsync(User, newTask, TodoTaskOperations.Create);
                if(!isAuthorized.Succeeded)
                {
                    return Forbid();
                }
                _repo.AddNewToDo(newTask);
                await _repo.SaveChanges();
                return RedirectToAction("Results", "Folder", new {id = folderIdVal});
            }
            return Redirect("/todotask/add");
        }
        //GET /<controller>/EditTask
        public async Task<IActionResult> EditTask(int id, int? folderId = null)
        {
            ToDoTask task = _repo.GetTodoById(id);
            ViewBag.folderId_e = null;
            if(folderId != null)
            {
                ViewBag.folderId_e = task.FolderId;
            }
            if(task == null)
            {
                return NotFound();
            }

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, task, TodoTaskOperations.Update);

            if(!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            ViewBag.taskToEdit = task;
            //I pass in ViewBag.taskToEdit.Body because the body text is stored in a textarea and due to ASP.NET rules, I have to instantiate the viewModel with the
            //Body description so that it properly shows, instead of just putting a temporary placeholder attribute. 
            List<Folder> folders = _repo.GetFoldersByUserId(UserManager.GetUserId(User)).ToList();
            AddToDoTaskViewModel viewModel = new AddToDoTaskViewModel(ViewBag.taskToEdit.Body, folders);
            return View(viewModel);
        }

        //POST /<controller>/EditTask
        [HttpPost]
        public async Task<IActionResult> EditTask(AddToDoTaskViewModel viewModel, int? folderId_e = null)
        {
            if(ModelState.IsValid)
            {

                ToDoTask editedTaskOnDB = _repo.GetTodoById(viewModel.Id);
                if(editedTaskOnDB == null)
                {
                    return NotFound();
                }

                var isAuthorized = await AuthorizationService.AuthorizeAsync(User, editedTaskOnDB, TodoTaskOperations.Update);

                if(!isAuthorized.Succeeded)
                {
                    return Forbid();
                }

                ToDoTask editedTask = new ToDoTask
                {
                    Id = viewModel.Id,
                    Title = viewModel.Title,
                    Body = viewModel.Body,
                    IsImportant = viewModel.IsImportant,
                    CreatedOn = _repo.GetTodoById(viewModel.Id).CreatedOn,
                    IsCompleted = viewModel.IsCompleted,
                    FolderId = viewModel.FolderId,
                    OwnerID = editedTaskOnDB.OwnerID
                };

                _repo.UpdateTask(editedTask);
                
                await _repo.SaveChanges();
                return RedirectToAction("Results","Folder", new {id = folderId_e});
            }
            return Redirect("/todotask/edit/" + viewModel.Id);
        }
        public async Task<IActionResult> DeleteTask(int id, int? folderId = null)
        {
            ToDoTask todoToRemove = _repo.GetTodoById(id);
            if(todoToRemove == null)
            {
                return NotFound();
            }

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, todoToRemove, TodoTaskOperations.Delete);

            if(!isAuthorized.Succeeded)
            {
                return Forbid();
            }
            _repo.DeleteTodo(todoToRemove);
            await _repo.SaveChanges();
            return RedirectToAction("Results", "Folder", new {id = folderId});
        }
        //GET /<controller>/BulkDelete
        public async Task<IActionResult> BulkDelete(int? folderId = null)
        {
            var currentUserId = string.Empty;
            List<ToDoTask> tasks;
            if(folderId == null)
            {
                currentUserId = UserManager.GetUserId(User);
                tasks = (List<ToDoTask>)await _repo.GetTodos(currentUserId);
            } else
            {
                int folderIdNotNull = (int)folderId;
                tasks = _repo.GetTodosByFolderId(folderIdNotNull).ToList();
            }
            ViewBag.folderId_bd = folderId;
            return View(tasks);
        }

        //POST /<controller>/BulkDelete
        [HttpPost]
        public async Task<IActionResult> BulkDelete(int[] idsToRemove, int? folderId_bd = null) //ids is empty. Need to debug this. checked checkboxes won't append their value to the array. 
        {
            foreach(int id in idsToRemove)
            {
                ToDoTask todoToDelete = _repo.GetTodoById(id);
                if (todoToDelete == null)
                {
                    return NotFound();
                }

                var isAuthorized = await AuthorizationService.AuthorizeAsync(User, todoToDelete, TodoTaskOperations.Delete);

                if (!isAuthorized.Succeeded)
                {
                    return Forbid();
                }
                _repo.DeleteTodo(todoToDelete);
            }
            await _repo.SaveChanges();
            return RedirectToAction("Results", "Folder", new {id = folderId_bd});
        }

        //GET /<controller>/Search
        [HttpPost]
        public async Task<IActionResult> Search(string userInput, int? folderId = null)
        {
            List<ToDoTask> todos = new List<ToDoTask>();
            if(folderId == null)

To-Do/To-Do/Views/ToDoTask/Add.cshtml
 @using To_Do.Models;
@using To_Do.ViewModels;

@model AddToDoTaskViewModel;

<form method="post" asp-controller="ToDoTask" asp-action="Add" asp-route-folderId = "@ViewBag.folderId">
    <div class="form-group">
        <label asp-for="Title">Title: <input type="text" asp-for="Title" /></label>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Body">Body: <textarea asp-for="Body" rows="10" cols="50" maxlength="1000"></textarea></label>
        <span asp-validation-for="Body" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsImportant">Mark as important?: <input type="checkbox" asp-for="IsImportant"/></label>
    </div>
    <div class="form-group">
        @if(ViewBag.folderId == null)
        {
            <label asp-for="FolderId">Add to folder</label>
            <select asp-for="FolderId" asp-items="Model.AvailFolders">
                <option disabled selected>Please select...</option>
            </select>
        } 
    </div>
    <input type="submit" value="Add To-Do" />
</form>

To-Do/To-Do/Views/ToDoTask/BulkDelete.cshtml
@using To_Do.Models;
@model List<ToDoTask>

<head>
    <script src="~/js/site.js"></script>
</head>

<a asp-controller="ToDoTask" asp-action="Index">< Back</a>
<form method="post" asp-controller="ToDoTask" asp-action="BulkDelete" asp-route-ids="idsToRemove" asp-route-folderId_bd="@ViewBag.folderId_bd">
        @foreach(var task in Model)
        {
            <div class="form-group">
                <label>
                    <input style="transform: scale(1.5);" type="checkbox" name="idsToRemove" value="@task.Id"/>
                    <span>@task.Title</span>
                </label>
            </div>
        }
        <input id="selectBtn" class="btn btn-outline-primary" type="button" value="Select All"/>
        <input id="deselectBtn" class="btn btn-outline-secondary" type="button" value="Deselect All"/>

    <input type="submit" value="Delete Selected" class="btn btn-danger"/>
</form>

To-Do/To-Do/Views/ToDoTask/EditTask.cshtml
@using To_Do.Models;
@using To_Do.ViewModels;


@model AddToDoTaskViewModel;

<p style="display:none;">
    @Model.Id = @ViewBag.taskToEdit.Id;
</p>
<form method="post" asp-controller="ToDoTask" asp-action="EditTask" asp-route-folderId_e="@ViewBag.folderId_e">
    <div class="form-group">
        <label asp-for="Title">Title: <input type="text" asp-for="Title" value="@ViewBag.taskToEdit.Title"/></label>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Body">Body: <textarea asp-for="Body" placeholder="@ViewBag.taskToEdit.Body" rows="10" cols="50" maxlength="1000"></textarea></label>
        <span asp-validation-for="Body" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="IsImportant">Mark as important?: <input type="checkbox" asp-for="IsImportant" checked="@ViewBag.taskToEdit.IsImportant"/></label>
    </div>
    <div class="form-group">
        <label asp-for="IsCompleted">Mark as completed?: <input type="checkbox" asp-for="IsCompleted" checked="@ViewBag.taskToEdit.IsCompleted" /></label>
    </div>
    <div class="form-group">
        <label asp-for="FolderId">Change folder</label>
        <select asp-for="FolderId" asp-items="Model.AvailFolders">
            <option disabled selected>Please select...</option>
        </select>
    </div>
    <input type="submit" value="Save" />
</form>

To-Do/To-Do/Views/ToDoTask/Index.cshtml
@using To_Do.Models;
@model List<ToDoTask>
<head>
    <link href="~/css/ToDoTaskIndexStyles.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/36af15ca2b.js" crossorigin="anonymous"></script>
</head>

<div>
    <a style="color:rgb(100,100,100);" asp-controller="Folder" asp-action="Index">
        < Folders
    </a>
</div>

<h1 class="indexPageTitle">
    @ViewBag.title
    <a style="color:inherit;" asp-area="" asp-controller="ToDoTask" asp-action="Add" asp-route-folderId="@ViewBag.folderId">
        <i class="fa-solid fa-square-plus"></i>
    </a>
</h1>

@if (Model.Count <= 0)
{

    <span>Nothing here yet!</span>
}
else
{
    <div>
        <form method="post" asp-controller="ToDoTask" asp-action="Search" asp-route-folderId="@ViewBag.folderId">
            <input style="border-style:none; border-bottom: 1px solid gray;" type="text" id="userInput" name="userInput" placeholder="Search..." />
            <input type="submit" value="🔍︎">
        </form>

    </div>
    <div>
        <div style="width:50%; float:left">
@*            <form method="post" asp-action="EditComplete" asp-controller="ToDoTask">
*@                <table style="width:75%; margin-top: 5%;">
                    @foreach (ToDoTask todo in Model)
                    {
                        <tr class="theTasks" data-row="row @todo.Id">
@*                            <td>
                                <input type="checkbox" class="roundCheckbox" data-row="row @todo.Id" name="IsCompleted" value="true" onchange="this.form.submit()" @(todo.IsCompleted ? "checked" : "")/>
                            </td>*@
                            <td class="todoText @(@todo.IsCompleted ? "strikethrough" : "")" data-row="row @todo.Id">
                                <p class="markedImportantSign">@(@todo.IsImportant == true ? "!" : "")</p>
                            </td>
                            <td class="todoText @(@todo.IsCompleted ? "strikethrough" : "")" data-row="row @todo.Id">
                                <p class="taskTitle">@todo.Title</p>
                            </td>
@*                            <td>
                                <input type="hidden" name="Id" value="@todo.Id"/>
                            </td>*@
                            <td class="EditDeleteLinks">
                                <a style="color:inherit;visibility:hidden;" asp-controller="ToDoTask" asp-action="EditTask" asp-route-id="@todo.Id" asp-route-folderId="@ViewBag.folderId">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                            </td>
                            <td class="EditDeleteLinks">
                                <a style="color:inherit;visibility:hidden;" asp-controller="ToDoTask" asp-action="DeleteTask" asp-route-id="@todo.Id" asp-route-folderId="@ViewBag.folderId">
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </table>
@*            </form>
*@
            <a style="color:red;" asp-controller="ToDoTask" asp-action="BulkDelete" asp-route-folderId="@ViewBag.folderId">Select To Delete</a>
        </div>

        <div style="width: 50%; float:right; margin-top: 3%;">
            @foreach(ToDoTask todo in Model)
            {
                <div class="taskDesc" style="display:none;" data-row="row @todo.Id">
                    <div class="taskDescTitle">
                        @if(todo.IsCompleted == true)
                        {
                            <i class="fa-solid fa-circle-check"></i>
                        }
                        @todo.Title
                        <p class="taskDescTitleImportant">
                            @(todo.IsImportant ? "Marked important" : "")
                        </p>
                        <p class="taskDateCreated">Created on @todo.CreatedOn.ToLongDateString() at @todo.CreatedOn.ToShortTimeString()</p>
                        <p class="taskDateCreated">Last edited on @todo.LastEditedOn.ToLongDateString() at @todo.LastEditedOn.ToShortTimeString()</p>
                    </div>
                    <div class="taskDescBody">@todo.Body</div>
                </div>
            }
        </div>
    </div>
}
<script src="~/js/strikethroughTask.js"></script>
<script src="~/js/site.js"></script>